name = "bss"
license = "Apache"
licenselink = "https://github.com/blackhole12/ponion/blob/master/LICENSE"
description = "A theme for Black Sphere Studios based on Beg"
homepage = "https://github.com/Black-Sphere-Studios/black-sphere-studios.github.io"
tags = ["company"]
features = ["blog"]
min_version = 0.15

[author]
  name = "Erik McClure"
  homepage = "https://github.com/blackhole12"

# If porting an existing theme
[original]
    name = "Daisuke Tsuji"
    homepage = "http://yet.unresolved.xyz/"
  repo = "https://github.com/dim0627/hugo_theme_beg/tree/2162885d5c58045cb6be9673329b4c22c035b74f"

